apiVersion: core.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: openstackdataplanenode-sample
spec:
  name: edpm-compute-0.localdomain
  hostName: edpm-compute-0.localdomain
  networkConfig:
    template: templates/net_config_bridge.j2
  networks:
    - network: management
      fixedip: 192.168.24.1/24
  managed: false
  managementNetwork: management

